### ISSUE TITLE
Questions about generalization

### ISSUE THREAD

**Issue by YuyanHuang** [chtsy/buol#2]
1.If I don't use the model front3d.pth to test the image demo.png, but use the model matterport3d.pth, the effect is not ideal. Isn't the model pre-trained on the front3d dataset?

2.If we use our own bedroom scene type pictures to test, no matter whether we use front3d.pth or matterport3d.pth to test, there is no formed object in the fly file. Have you done similar tests? Is it a question of generalization ability?

Thanks!

**Comment by chtsy** [comment]
The pre-trained model on front3d is used to speed up convergence. When training on matterport3d, the model may forget the knowledge on front3d. You can try to add front3d data when training matterport3d to enhance generalization.

Due to the poor generalization of depth estimation, it is difficult to train a general model to reconstruct all types of scenes well. Therefore, when the scene type changes, retraining is required.  You can also try to use a more generalized depth estimation model to enhance model generalization.
